"""
Django settings for orets project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-cl%zd*9vqj4i+80r3rox%h4*vm1#&gl-vt^is-cqqckf9m(de6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = [
    'localhost', 'f9d8-102-215-111-41.ngrok-free.app',
    '127.0.0.1',
   '5a7d-102-222-233-196.ngrok-free.app',
   'af6f-41-75-177-106.ngrok-free.app',
   'https://af6f-41-75-177-106.ngrok-free.app/login# Your actual domain','https://f9d8-102-215-111-41.ngrok-free.app '
        # If using ngrok
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'crispy_forms',
    'core.apps.CoreConfig',
    'crispy_bootstrap5',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whatsapp',
     'payments',
    'ai',
    'products', 
    'orders',
    'notifications',
    'analytics',
]

CSRF_TRUSTED_ORIGINS = [
    'https://5a7d-102-222-233-196.ngrok-free.app','https://af6f-41-75-177-106.ngrok-free.app', 'https://f9d8-102-215-111-41.ngrok-free.app '
    # Add other trusted domains as needed
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    #'core.middleware.ProfileCompletionMiddleware',
    'core.middleware.ThreadLocalRequestMiddleware',
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    

]

ROOT_URLCONF = "orets.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Must include this
        
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # ... existing processors ...
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Required
                'django.contrib.auth.context_processors.auth',  # Required
                'django.contrib.messages.context_processors.messages'
            ],
        },
    },
]

WSGI_APPLICATION = "orets.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# Add your apps to INSTALLED_APPS
SESSION_COOKIE_SECURE = True  # For HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # Or 'None' if needed
SESSION_COOKIE_DOMAIN = None  # Or your ngrok domain without protocol


# Add these important settings
WHATSAPP_BUSINESS_API_URL = 'https://graph.facebook.com/v19.0/'
WHATSAPP_BUSINESS_API_TOKEN = os.getenv('WHATSAPP_API_TOKEN')
WHATSAPP_BUSINESS_PHONE_NUMBER_ID = os.getenv('WHATSAPP_PHONE_NUMBER_ID')

# For the AI component
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')  # Or whichever LLM you're using

# For media files (product images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
LOGIN_REDIRECT_URL = 'core:dashboard'  # Update this line
LOGIN_URL = 'login'  # Default is 'accounts/login/'
AUTH_USER_MODEL = 'core.business'


#LOGIN_REDIRECT_URL = 'home'  # Where to redirect after login
LOGOUT_REDIRECT_URL = 'home'  # Where to redirect after logout
MEDIA_URL = '/media/'
MEDIA_URL = 'http://localhost:8000/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
################ DEBUGGING ###########
print("TEMPLATE DIRS:", [os.path.join(BASE_DIR, 'templates')])

# WhatsApp Integration
TWILIO_ACCOUNT_SID = 'ACa7e933ebca3418f5176c3571b7c0c25f'
TWILIO_AUTH_TOKEN = '26be5164e9c0a6aa90950797e14653a6'
OPENAI_API_KEY = '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'
WHATSAPP_BUSINESS_NUMBER = "whatsapp:+14155238886"  # Your Twilio number



